### ISSUE TITLE
vbguest doesn't handle proxies

### ISSUE THREAD

**Issue by TobyHFerguson** [dotless-de/vagrant-vbguest#146] opened 2015-01-27 23:20 UTC
My host environment (Oracle Linux) requires the use of proxies, and therefore so too does my guest environment (also Oracle Linux) - but vbguest has no settings to allow one to inject a proxy in, and therefore the yum update executed by vbguest fails :-(

The fix is to provide something like 'vbguest.proxy = WPAD or PROXY'  which will cause yum or its equivalent with other packaging mechanisms to use the correct proxy ...

**Comment by ilpianista** [comment] 2017-07-06 09:40
Isn't this a duplicate of #77?

(I confirm vagrant-proxyconf solved the issue for me)

**Closed** 2019-01-18 20:46 UTC
Labels: wontfix
