### ISSUE TITLE
"vagrant up" fails under Vbguest 0.28.0. Downgrading to 0.21.0 solves the issue

### ISSUE THREAD

**Issue by cvquesty** [dotless-de/vagrant-vbguest#399] opened 2020-12-22 17:14 UTC
Under the new "Big Sur", running "vagrant up" when vagrant-vbguest is installed (and used) causes an error whereby a mount is looked for and generates a condition where vagrant-vbguest will not run and fails hard. The error output is:

```
Complete!
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.genesisadaptive.com
 * extras: mirror.rackspace.com
 * updates: mirror.umd.edu
No package kernel-devel-3.10.0-1127.el7.x86_64 available.
Error: Nothing to do
Unmounting Virtualbox Guest Additions ISO from: /mnt
umount: /mnt: not mounted
==> master: Checking for guest additions in VM...
    master: No guest additions were detected on the base box for this VM! Guest
    master: additions are required for forwarded ports, shared folders, host only
    master: networking, and more. If SSH fails on this machine, please install
    master: the guest additions and repackage the box to continue.
    master:
    master: This is not an error message; everything may continue to work properly,
    master: in which case you may ignore this message.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

umount /mnt

Stdout from the command:



Stderr from the command:

umount: /mnt: not mounted
```

Siply backporting vagrant-vbguest to 0.21.0 resolves the issue.

**Comment by fnordfish** [comment] 2020-12-22 17:17
Possibly duplicate of #398

**Comment by cvquesty** [comment] 2020-12-22 17:35
I don’t think so.  RHEL8 is not involved in any way

**Comment by cvquesty** [comment] 2020-12-22 17:43
I checked #398 and was able to determine from looking at the code that the state behavior is not present in that ticket.  Can I provide further illumination or logging to assist with the issue?

**Comment by fnordfish** [comment] 2020-12-22 17:48
From your log `No package kernel-devel-3.10.0-1127.el7.x86_64 available.` I take it you are using CentOS7 ... hence the guess that the old "enable repo" fixes your problem.

For now, you could use let vbguest update the kernel in your box (https://github.com/dotless-de/vagrant-vbguest#installer-specific-options-installer_options : `config.vbguest.installer_options = { allow_kernel_upgrade: true }` )

**Comment by jonas** [comment] 2021-02-26 00:23
I can confirm that `allow_kernel_upgrade: true` fixes this issue for `bento/centos-7.8`.

**Comment by Paladinhanxiao** [comment] 2021-05-18 10:16
```
vagrant plugin uninstall vagrant-vbguest
vagrant plugin install vagrant-vbguest --plugin-version 0.21
```
it’s work for me

**Comment by xinatcg** [comment] 2021-06-21 07:36
> From your log `No package kernel-devel-3.10.0-1127.el7.x86_64 available.` I take it you are using CentOS7 ... hence the guess that the old "enable repo" fixes your problem.
> 
> For now, you could let vbguest update the kernel in your box (https://github.com/dotless-de/vagrant-vbguest#installer-specific-options-installer_options : `config.vbguest.installer_options = { allow_kernel_upgrade: true }` )

this resolve my issue, using 0.30.0 and reload, it will install the package to the vm after detect: `[default] No Virtualbox Guest Additions installation found.` 

```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
end
```

**Comment by OneCodeMonkey** [comment] 2021-08-09 03:53
This works !
add this line in `provider` config:
`config.vbguest.installer_options = { allow_kernel_upgrade: true }`

@fnordfish  thks ~

**Comment by andrewfawcett** [comment] 2021-09-08 22:45
I experience this after upgrading to the latest VirtualBox (6.1.26). Then vagrant-vbguest (0.24) was preventing my machine from starting up. Upgrading to latest (0.30.0) got me a little further, but I would get a similar failure after checking for guest additions. I tried the latest CentOS 7 (v2004.01) and CentOS 8 images (2011.0) but neither helped. Also tried allow_kernel_upgrade. I really liked this plugin, but I've reverted to rsync until this bug is fixed.

**Comment by maltewhiite** [comment] 2021-09-15 08:08
> From your log `No package kernel-devel-3.10.0-1127.el7.x86_64 available.` I take it you are using CentOS7 ... hence the guess that the old "enable repo" fixes your problem.
> 
> For now, you could let vbguest update the kernel in your box (https://github.com/dotless-de/vagrant-vbguest#installer-specific-options-installer_options : `config.vbguest.installer_options = { allow_kernel_upgrade: true }` )

What file do I place that line in?

**Comment by Neko0258** [comment] 2022-02-23 07:47
> > From your log `No package kernel-devel-3.10.0-1127.el7.x86_64 available.` I take it you are using CentOS7 ... hence the guess that the old "enable repo" fixes your problem.
> > For now, you could let vbguest update the kernel in your box (https://github.com/dotless-de/vagrant-vbguest#installer-specific-options-installer_options : `config.vbguest.installer_options = { allow_kernel_upgrade: true }` )
> 
> What file do I place that line in?

in vagrantfile

**Comment by maltewhiite** [comment] 2022-02-23 13:57
> > > From your log `No package kernel-devel-3.10.0-1127.el7.x86_64 available.` I take it you are using CentOS7 ... hence the guess that the old "enable repo" fixes your problem.
> > > For now, you could let vbguest update the kernel in your box (https://github.com/dotless-de/vagrant-vbguest#installer-specific-options-installer_options : `config.vbguest.installer_options = { allow_kernel_upgrade: true }` )
> > 
> > 
> > What file do I place that line in?
> 
> in vagrantfile

I ended up changing to Ubuntu instead

**Comment by AndresBott** [comment] 2022-07-17 22:36
I'm still facing this issue with image "debian/bullseye64" and version v0.30.v
downgrading to v0.21.0 or _config.vbguest.installer_options = { allow_kernel_upgrade: true }_ did not help

**Comment by fatemealizade** [comment] 2022-11-01 12:14
`vagrant plugin uninstall vagrant-vbguest` solved this issue for me!
Don't give any vbgues addition to vagrant and virtualbox :))

**Comment by andresbott** [comment] 2022-11-01 12:48
For whom might interest, I ended up baking my own image.
check the details here: https://gist.github.com/andresbott/b09b4fb16113f02e20fa0ef39025064c

**Comment by bruvv** [comment] 2023-01-10 22:03
Running `rockylinux/9`, same error.  downgrading to v0.21.0 or config.vbguest.installer_options = { allow_kernel_upgrade: true } did not help

**Comment by maisonhai3** [comment] 2023-07-13 01:58
> From your log `No package kernel-devel-3.10.0-1127.el7.x86_64 available.` I take it you are using CentOS7 ... hence the guess that the old "enable repo" fixes your problem.
> 
> For now, you could let vbguest update the kernel in your box (https://github.com/dotless-de/vagrant-vbguest#installer-specific-options-installer_options : `config.vbguest.installer_options = { allow_kernel_upgrade: true }` )

This works in my case.

I use the code below to create a VM with CentOS 9, then got the same problem.
Then this solution fixes it.

```
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provider "virtualbox" do |vb|
     vb.memory = "600"
   end

  end
```

**Comment by maisonhai3** [comment] 2023-07-13 02:15
***allow_kernel_upgrade: true*** workaround.

However, this code updates kernels EVERY SINGLE TIME while a box is set up, which costs a huge amount of time.

**Comment by fnordfish** [comment] 2023-07-13 06:48
As an explainer: The `allow_kernel_upgrade` is there so that the matching Kernel header packages can be installed. This is, because CentOS* removes “old” Kernel header packages from its registry. We don’t **need** to update the Kernel, but it is the only way to get matching headers. 

The Solution™ would be to use a base box which has the matching Kernel headers, maybe even all the other dependencies needed to compile guest additions, already installed.

**Comment by bisrikarim** [comment] 2023-08-10 18:38
> This works ! add this line in `provider` config: `config.vbguest.installer_options = { allow_kernel_upgrade: true }`
> 
> @fnordfish thks ~

That works for my, thank you

**Comment by bahmanm** [comment] 2023-09-09 11:28
Using v0.31.0 w/ VirtualBox 7.0.10 on openSUSE Tumbleweed:  
In my case all I had to do was to add the guest additions ISO file to the Media Manager.  vbguest auto-detected the ISO and everything went smoothly w/o `allow_kernel_upgrade` or `auto_reboot`.

![image](https://github.com/dotless-de/vagrant-vbguest/assets/315582/f5d419e7-7d8e-459c-8106-043cc8556d72)

**Closed** 2023-12-17 15:28 UTC
Labels: wontfix
