### ISSUE TITLE
Ensure vbguest dependencies can be installed

### ISSUE THREAD

**Issue by Kiarashz** [dotless-de/vagrant-vbguest#297] opened 2018-05-14 06:23 UTC
When provisioning new CentOS 7 found that vbguest plugin tries to install non-existing version of kernel-devel package. It is not this plugin issue but CentOS team not updating their vagrant box before removing deprecated packages. 
However, below change can save users from spending time on resolving these sort of issues.
```
git diff
diff --git a/lib/vagrant-vbguest/installers/redhat.rb b/lib/vagrant-vbguest/installers/redhat.rb
index a52e72c..0249a34 100644
--- a/lib/vagrant-vbguest/installers/redhat.rb
+++ b/lib/vagrant-vbguest/installers/redhat.rb
@@ -16,7 +16,7 @@ module VagrantVbguest
 
     protected
       def install_dependencies_cmd
-        "yum install -y #{dependencies}"
+        "yum -y install kernel && yum install -y #{dependencies}"
       end
 
       def dependencies
```

**Comment by fnordfish** [comment] 2018-05-14 06:50
Hi @Kiarashz. Thanks for getting involved. There has been already quite a lot discussions about CentOS‘ kernel packages.

Hover, I‘m going to accept pull requests that add an opt-in config `upgrade_kernel` (or alike) that would check if header packages for current kernel exist and upgrade the kernel otherwise.  

As for now, Closing as a duplicate of #141, #153, #223 and #231

--  
Robert Schulze

**Closed** 2018-05-14 10:32 UTC
