### ISSUE TITLE
vagrant-vbguest doesn't work with vagrant-reload

### ISSUE THREAD

**Issue by ethanmdavidson** [dotless-de/vagrant-vbguest#333] opened 2019-04-18 20:17 UTC
Recently upgraded virtualbox from 6.0.4 to 6.0.6. The box I'm using was built with 6.0.4 guest additions, so when I next upped the box, vbguest attempted to install the new guest addition. However, it doesn't seem to install correctly. At the very end of vagrant up, I see the following output:
```shell
[devapp] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
bash: line 4: setup: command not found
==> devapp: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 4: setup: command not found
```
and `vagrant vbguest --status` reports:
```shell
[devapp] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
```

However, when I comment out `devapp.vm.provision :reload` the vagrant up performs perfectly, although it seems that virtualbox is not reporting its version correctly:
```shell
PS> vagrant vbguest --status
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.4
VBoxService inside the vm claims: 6.0.6
Going on, assuming VBoxService is correct...
[devapp] GuestAdditions 6.0.6 running --- OK.
```
but VirtualBox is reporting 6.0.6 when I open the program and check its "about" section:
```
VirtualBox Graphical User Interface
Version 6.0.6 r130049 (Qt5.6.2)
Copyright © 2019 Oracle Corporation and/or its affiliates. All rights reserved.
```

It is installing from the local .iso file, rather than downloading anything. The vagrantfile having this issue is fairly large and logs a lot of stuff while upping, so I won't post it here. I'll try to put together a simple example that demonstrates this issue. 

Host details:
- Windows 10
- VirtualBox 6.0.6
- Vagrant 2.2.4

Guest details:
- Oracle Linux 7 (box name "ol7-latest", from https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box
- Base box has guest additions 6.0.4

**Comment by byronclark** [comment] 2019-04-19 01:02
I'm seeing the same issue using an Ubuntu 16.04 guest. My guess is that something is broken in the VirtualBox 6.0.6 guest additions installer.

**Comment by alvaro-canepa** [comment] 2019-04-20 09:26
I have the same issue with Homestead and Virtualbox 6.0.6.

Adding this to Vagrantfile solve the problem:
```
if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
end
```

**Comment by brianmowens** [comment] 2019-04-20 23:30
Confirming that I am also seeing this same issue. Same error message as posted by @ethanmdavidson 

Host OS: Windows 10
Vagrant: 2.2.4
VirtualBox: 6.0.6 r130049 (Qt5.6.2)
Box: ubuntu/xenial64 - 20190419.0.0

**Comment by carlosefr** [comment] 2019-04-22 10:55
I'm seeing the same think with CentOS as guest.

**Comment by carlosefr** [comment] 2019-04-22 11:03
At a first glance, it seems like `find_tool` isn't finding `vboxadd` here:

https://github.com/dotless-de/vagrant-vbguest/blob/16620b9e05ff02f8bee9ca7e0867da26b0427e75/lib/vagrant-vbguest/installers/linux.rb#L114

The search directories indeed don't include any path where `vboxadd` may be found. Compare the paths in the code:

https://github.com/dotless-de/vagrant-vbguest/blob/16620b9e05ff02f8bee9ca7e0867da26b0427e75/lib/vagrant-vbguest/installers/linux.rb#L174-L182

With the paths in my VM:

```
$ locate vboxadd | grep 'vboxadd$'
/etc/kernel/postinst.d/vboxadd
/etc/kernel/prerm.d/vboxadd
/opt/VBoxGuestAdditions-6.0.6/init/vboxadd
/usr/sbin/rcvboxadd
```

**Comment by carlosefr** [comment] 2019-04-22 12:23
Adding this to the `Vagrantfile` works somewhat, as the error doesn't appear in the first boot:
```
    config.vm.provision "shell", inline: 'test -x /usr/bin/VBoxControl -a ! -d /lib/VBoxGuestAdditions && ' \
                                         'ln -s /opt/VBoxGuestAdditions-$(VBoxControl version | ' \
                                         'perl -ne \'print $1 if /Version\s+([^\s]+)$/i\')/init /lib/VBoxGuestAdditions'
```

However, it *always* builds the modules. Seems like the proper option to `vboxadd` is now `quicksetup` instead of `setup`.

**Comment by cvquesty** [comment] 2019-04-22 14:32
Interesting.  In ssh'ing to the child, I manually look for and run the command, and vboxadd complains it doesn't have that option.  Trying to nail down the specifics on this one.  I had to remove the vagrant-vaguest plugin for the time being so I can work but help certainly appreciated on this one.

**Comment by haxorof** [comment] 2019-04-22 16:53
I bumped into the same issue in centos/7 and it seems that the first installation works as expected. However, if you reload then `vagrant-vbguest` prints that the guest additions is in fact install but not running:
```
[default] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
```

Debug output:
```
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: VBoxService --version (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: lsmod | grep vboxsf (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 1
DEBUG vbguest-machine: Current states for VM 'default' are : guest_version=6.0.6 : host_version=6.0.6 : running=false
DEBUG vbguest-machine: Running command rebuild from runlist
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:         for c in /usr/lib/i386-linux-gnu/VBoxGuestAdditions/vboxadd /usr/lib/x86_64-linux-gnu/VBoxGuestAdditions/vboxadd /usr/lib64/VBoxGuestAdditions/vb
oxadd /usr/lib/VBoxGuestAdditions/vboxadd /lib64/VBoxGuestAdditions/vboxadd /lib/VBoxGuestAdditions/vboxadd /etc/init.d/vboxadd; do
          if test -x "$c"; then
            echo $c
            break
          fi
        done
 (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  setup (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: stderr: bash: line 4: setup: command not found
```

If the above log it is visible that lsmod is used to determine if it is running or not. Looking at that lsmod at the time it failed it look like this:
```
[vagrant@localhost ~]$ lsmod | grep vbox
vboxvideo              35874  1
ttm                   114635  1 vboxvideo
drm_kms_helper        179394  1 vboxvideo
drm                   429744  4 ttm,drm_kms_helper,vboxvideo
vboxguest             347610  1
```

So I did a small change in how running state is determined for linux into this:

```ruby
communicate.test('lsmod | egrep "vboxsf|vboxguest"', opts, &block)
```

Then the it will determine guest additions is running and everything seems to work and after boot the lsmod looks like this:
```
[vagrant@localhost ~]$ lsmod | grep vbox
vboxsf                 81012  1
vboxvideo              35874  1
ttm                   114635  1 vboxvideo
drm_kms_helper        179394  1 vboxvideo
vboxguest             347610  2 vboxsf
drm                   429744  4 ttm,drm_kms_helper,vboxvideo
```

Hope this will give some more info to quickly resolve the issue. 😄 

Cheers!

**Comment by carlosefr** [comment] 2019-04-22 16:57
So there seems to be two problems here, because with @haxorof's fix, the original problem will still appear if the VM's kernel is upgraded after the initial installation (it will try to rebuild, and will fail).

**Comment by carlosefr** [comment] 2019-04-22 17:00
Just a thought: I believe checking for a loaded `vboxguest` doesn't allow to conclude that the additions are running, because isn't that module included out-of-the-box in most distros?

**Comment by haxorof** [comment] 2019-04-22 17:03
@carlosefr : Might be that it is not safe to look for just `vboxguest`. I have just checked in CentOS right now.

To handle the kernel upgrade it might be necessary to also look for `/sbin/rcvboxadd` which is a symbolic link and it works with the setup argument
```
[vagrant@localhost ~]$ file /sbin/rcvboxadd
/sbin/rcvboxadd: symbolic link to `/opt/VBoxGuestAdditions-6.0.6/init/vboxadd'

[vagrant@localhost ~]$ sudo /sbin/rcvboxadd setup
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
3.10.0-957.5.1.el7.x86_64.
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted
```

**Comment by carlosefr** [comment] 2019-04-22 17:12
Perhaps it would be better to look for the `vboxsf.ko` file on disk, for the running kernel. If not present, then rebuild and restart, otherwise try to restart the service (or wait, because what might be happening is that the service is still starting when the check is performed).

Or check **both** for a loaded `vboxguest` and the presence of `vboxsf.ko` on disk for the running kernel. This might make it safe to assume that the loaded `vboxguest` indeed comes from the guest additions (except on the first boot right after installing them).

**Comment by haxorof** [comment] 2019-04-22 17:20
Might be safe enougth yes.

I looked into the `/sbin/rcvboxadd` file to see how it determines running state add it is a bit odd that function `running_vboxsf` is defined but never used in the script. 😄 Only `running_vboxguest`and `running_vboxadd` is used what I can see.

```
running_vboxguest()
{
    lsmod | grep -q "vboxguest[^_-]"
}

running_vboxadd()
{
    lsmod | grep -q "vboxadd[^_-]"
}

running_vboxsf()
{
    lsmod | grep -q "vboxsf[^_-]"
}

running_vboxvideo()
{
    lsmod | grep -q "vboxvideo[^_-]"
}
```

**Comment by haxorof** [comment] 2019-04-22 17:43
FYI, just checked some Ubuntu and Debian version what it looks when running `lsmod`:
```
vagrant@ubuntu-xenial:~$ lsmod | grep vbox
vboxsf                 77824  2
vboxguest             331776  2 vboxsf
vboxvideo              40960  1
drm_kms_helper        155648  1 vboxvideo
ttm                    98304  1 vboxvideo
drm                   364544  4 ttm,drm_kms_helper,vboxvideo
```

```
vagrant@stretch:~$ lsmod | grep vbox
vboxsf                 77824  1
vboxvideo              36864  1
ttm                    98304  1 vboxvideo
drm_kms_helper        155648  1 vboxvideo
vboxguest             327680  2 vboxsf
drm                   360448  4 vboxvideo,ttm,drm_kms_helper
```

**Comment by carlosefr** [comment] 2019-04-22 18:00
Opened PR #334, which seems to work for CentOS 7 and Debian 9.

**Comment by danepowell** [comment] 2019-04-25 13:16
Related:
- https://github.com/dotless-de/vagrant-vbguest/issues/278
- https://www.virtualbox.org/ticket/18598

**Comment by mowens3** [comment] 2019-04-26 15:46
I'm using the following steps to resolve this error on Ubuntu 18.04:
1) navigate to problematic vagrant directory and uninstall vbguest: `vagrant plugin uninstall vagrant-vbguest`
2) Add the following code to the respective Vagrantfile
`if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
end`
3) run `vagrant halt` followed by `vagrant up`

everything should work at this point.

**Comment by LukaszFormela** [comment] 2019-04-29 14:50
If none of the above worked for you, try downgrading vbguest to lower version, that worked for me on VB  6.0.6, Vagrant 2.2.4 and debian/jessie64:

`vagrant up (if it doesn't start, follow it by vagrant reload)
vagrant ssh
sudo su
cd /tmp
wget https://www.virtualbox.org/download/testcase/VBoxGuestAdditions_5.2.29-130064.iso
mkdir /media/VBoxGuestAdditions
mount -o loop,ro VBoxGuestAdditions_5.2.29-130064.iso /media/VBoxGuestAdditions
sh /media/VBoxGuestAdditions/VBoxLinuxAdditions.run
rm VBoxGuestAdditions_5.2.29-130064.iso
umount /media/VBoxGuestAdditions
rmdir /media/VBoxGuestAdditions
exit
exit`

In your Vagrantfile add the following:

`config.vbguest.auto_update = false`

Then do another vagrant reload.

**Comment by carlosefr** [comment] 2019-04-29 18:48
The 6.0.6 guest additions don't seem to support that kernel (either a regression, or a drop in support). That's an issue for the virtualbox bug tracker, I guess.

**Comment by xurizaemon** [comment] 2019-05-02 03:19
Ran into this also with VirtualBox 6.0.6. For the time being, removing `vagrant-vbguest` seems to have resolved the issue.

Before doing so, booting gave the "setup: command not found" error and the VM would run but be missing any synced_folders.

After `vagrant plugin uninstall vagrant-vbguest`, the VM booted and had synced folders once more.

**Comment by StoyanIvanovI** [comment] 2019-05-06 11:18
I ended up having to downgrade to VirtualBox 5.2.28 due to issues with shared folder permissions with any of the solutions above. This is definitely a bug with Guest Additions and potentially VirtualBox 6.0.6.

**Comment by xkrt** [comment] 2019-05-15 07:00
Same problem with fresh VBox/GuestAdds v6.0.8

**Comment by DonTermi** [comment] 2019-05-16 06:31
@LukaszFormela 

> wget https://www.virtualbox.org/download/testcase/VBoxGuestAdditions_5.2.29-130064.iso

`The requested URL /download/testcase/VBoxGuestAdditions_5.2.29-130064.iso was not found.`

**Comment by LukaszFormela** [comment] 2019-05-16 07:13
> @LukaszFormela
> 
> > wget https://www.virtualbox.org/download/testcase/VBoxGuestAdditions_5.2.29-130064.iso
> 
> `The requested URL /download/testcase/VBoxGuestAdditions_5.2.29-130064.iso was not found.`

Try this one instead:
http://download.virtualbox.org/virtualbox/5.2.30/VBoxGuestAdditions_5.2.30.iso

**Comment by robnagler** [comment] 2019-05-16 21:59
One of the problems is the name of the kernel module has changed to vboxguest. Another problem is that vboxadd is now rcvboxadd. The patch below works for us, because we only run CentOS 7 and Fedora. It's not a general fix.

```patch
*** .vagrant.d/gems/2.4.4/gems/vagrant-vbguest-0.17.2/lib/vagrant-vbguest/installers/linux.rb~  2019-05-09 12:26:46.000000000 -0600
--- .vagrant.d/gems/2.4.4/gems/vagrant-vbguest-0.17.2/lib/vagrant-vbguest/installers/linux.rb   2019-05-16 15:54:59.000000000 -0600
***************
*** 78,84 ****
          opts = {
            :sudo => true
          }.merge(opts || {})
!         communicate.test('lsmod | grep vboxsf', opts, &block)
        end

        # This overrides {VagrantVbguest::Installers::Base#guest_version}
--- 78,84 ----
          opts = {
            :sudo => true
          }.merge(opts || {})
!         communicate.test('systemctl is-active vboxadd-service.service', opts, &block)
        end

	# This overrides {VagrantVbguest::Installers::Base#guest_version}
***************
*** 111,117 ****
	# @yieldparam [String] type Type of the output, `:stdout`, `:stderr`, etc.
	# @yieldparam [String] data Data for the given output.
	def rebuild(opts=nil, &block)
!         communicate.sudo("#{find_tool('vboxadd')} setup", opts, &block)
	end

	# @param opts [Hash] Optional options Hash wich meight get passed to {Vagrant::Communication::SSH#execute} and firends
--- 111,117 ----
	# @yieldparam [String] type Type of the output, `:stdout`, `:stderr`, etc.
	# @yieldparam [String] data Data for the given output.
	def rebuild(opts=nil, &block)
!         communicate.sudo("/sbin/rcvboxadd setup", opts, &block)
	end

	# @param opts [Hash] Optional options Hash wich meight get passed to {Vagrant::Communication::SSH#execute} and firends
```

**Comment by carlosefr** [comment] 2019-05-17 09:32
@robnagler The `vboxguest` module has always existed (`vboxsf` depends on it), but what I think may have happened (I haven't checked) is that `vboxadd` stopped loading `vboxsf`when starting, instead deferring it to the moment when shared folders are mounted.

I didn't check for `vboxadd` being started on PR #334 because, as you mentioned, that would make it distribution specific.

**Comment by robnagler** [comment] 2019-05-17 14:53
@carlosefr got it, thanks. In #334 I wonder why you wouldn't also try `systemctl is-active vboxadd-service.service`, too. If the structure of the kernel modules changes, the higher level tests will probably still work.

**Comment by fnordfish** [comment] 2019-05-20 13:26
released #334 as v0.18.0

I'm closing this issue. If there's anything new, please feel free to reopen this one or create a new issue.

**Closed by fnordfish** 2019-05-20 13:26 UTC

**Comment by artlung** [comment] 2019-06-20 18:05
```if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
end``` 

...made this work for me. Vagrant version 2.2.4, MacOS 10.14.5

**Comment by nskgit** [comment] 2019-06-25 19:07
'vagrant plugin update' needs an update

**Comment by longyue0521** [comment] 2019-10-16 00:38
`vagrant plugin update` worked for me! :)
