### ISSUE TITLE
Seems to not working on Windows 10

### ISSUE THREAD

**Issue by julestruong** [dotless-de/vagrant-vbguest#187] opened 2015-12-23 21:36 UTC
http://stackoverflow.com/questions/34441503/cant-run-vagrant-up

**Comment by fnordfish** [comment] 2015-12-23 22:46
Can you please re-run with vagrants debugging turned on. To me it looks like the last commands where issued by vagrant and vaguest did complete.
Did you had an earlier version of vagrant and/or windows working, or is vagrant 1.8 + windows 10 your first try? (I'm trying to figure out what moving part might caused a problem)

**Comment by julestruong** [comment] 2016-01-05 17:37
ok i'm doing it right now  (posting result in minutes)

**Comment by fnordfish** [comment] 2016-01-06 07:52
Hi @julestruong, sorry I've didn't see your edit.
Closing as a duplicate of the more detailed #189

**Closed by fnordfish** 2016-01-06 07:52 UTC
