### ISSUE TITLE
Broken installation on CentOS 6.10

### ISSUE THREAD

**Issue by muglug** [dotless-de/vagrant-vbguest#320] opened 2019-01-04 16:08 UTC
This is problematic: https://github.com/dotless-de/vagrant-vbguest/blob/aa39d89dc588a4cbb60021c174f4a79f3e14d3b1/lib/vagrant-vbguest/installers/centos.rb#L45

When `rel` is `nil` (e.g. when `/etc/centos-release` is `"CentOS release 6.10 (Final)"` this means `yum` looks for a repo `C-base`, when it should (IMO) just be looking at `base`. When `yum` cannot find a repo the guest additions installation breaks, whereas when it can't find that package the installation succeeds as normal.

**Comment by fnordfish** [comment] 2019-01-04 16:20
good catch. Do you know which would be the correct repo to use, `C6.10-base` or would we need to add the patch-version like `C6.10.0-base`?

**Comment by spencerhakim** [comment] 2019-01-10 23:18
I'm hitting a similar issue with a custom 7.4 box, which for whatever reason tries to use the 7.6.1810 repo (which just throws `Error getting repository data for C7.6.1810-base, repository not found`). Why not just hardcode something like `--enablerepo=C*-base --enablerepo=C*-updates`? Wildcards are supported.

**Comment by fnordfish** [comment] 2019-01-11 11:06
@bstopp Can I get your two cents on this issue? Personally, the wildcard approach (`--enablerepo=C*-base`) sounds reasonable, but maybe there's a reason why using the specific release version is preferable.

**Comment by timcharper** [comment] 2019-01-16 17:56
@spencerhakim I can confirm this works for me. I've patched the following, locally:

```
 ~/.vagrant.d/gems/2.4.4/gems/vagrant-vbguest-0.17.1
10:55 $ diff -u lib/vagrant-vbguest/installers/centos.rb.old lib/vagrant-vbguest/installers/centos.rb
--- lib/vagrant-vbguest/installers/centos.rb.old	2019-01-16 10:55:13.000000000 -0700
+++ lib/vagrant-vbguest/installers/centos.rb	2019-01-16 10:52:00.000000000 -0700
@@ -42,7 +42,8 @@

       def install_kernel_devel(opts=nil, &block)
         rel = release_version
-        cmd = "yum install -y kernel-devel-`uname -r` --enablerepo=C#{rel}-base --enablerepo=C#{rel}-updates"
+        # cmd = "yum install -y kernel-devel-`uname -r` --enablerepo=C#{rel}-base --enablerepo=C#{rel}-updates"
+        cmd = "yum install -y kernel-devel-`uname -r` --enablerepo=C*-base --enablerepo=C*-updates"
         communicate.sudo(cmd, opts, &block)
       end
```

... and the issue has gone away.

**Comment by bstopp** [comment] 2019-01-16 20:34
I posted the update with specific repos so as to not enable more than necessary. I'm not that versed in the nuances so i didn't know if there might be conflict or other issues resulting from a `*` repo definition. (And on a person note, I don't like enabling more than is minimally necessary to perform any given task, feels "cleaner" to me. 🤷‍♂️ )

**Comment by fnordfish** [comment] 2019-01-18 10:20
Is there any way we can check if certain repo exists/ is available? So that we check if we can go `C#{rel}` or use `C*`as a fallback

**Comment by bstopp** [comment] 2019-01-19 14:55
If the repository doesn't exist in the list of known repos, yum will exit with an error:

```
[root@vagrant ~]# yum update --enablerepo=foo
Loaded plugins: fastestmirror


Error getting repository data for foo, repository not found
[root@vagrant ~]# 
```

**Comment by fnordfish** [comment] 2019-01-23 15:39
fixed in 0.17.2

**Closed by fnordfish** 2019-01-23 15:39 UTC

**Comment by fnordfish** [comment] 2019-01-23 15:42
@spencerhakim would mind to open a new issue regarding `kernel-lt`/`kernel-ml`

**Comment by danimop** [comment] 2019-09-19 19:19
I don't know if this should be added to this issue or a new one, but this is currently still broken for the newest release of the centos/7 vagrant box. The specific error I get is: 
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` --enablerepo=C*-base --enablerepo=C*-updates

Stdout from the command:

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.edatel.net.co
 * extras: mirror.edatel.net.co
 * updates: mirror.edatel.net.co

Stderr from the command:

http://vault.centos.org/7.6.1810/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
```
I think I pinned down the issue to this: https://bugs.centos.org/view.php?id=16408. There is a new release of CentOS but the old release is still not in the vault. The temporary solution was to switch to the _generic/centos7_ box and everything works. It seems this will be an ongoing issue in the 2 weeks or so between a new CentOS release and the time the old one gets uploaded to the vault.

Is it possible to have an option in the plugin to skip updating the repos? Or alternatively to prevent failing when the repo is not found?

**Comment by j3mdamas** [comment] 2019-09-20 09:45
I faced the same issue as @danimop. `generic/centos7` was not working for me due to Guest Additions version incompatilibity, so I went with the following work-around on my Vagrantfile:
```
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
```

But it would be nice if this got fixed. Thanks!

**Comment by danimop** [comment] 2019-09-20 15:55
@j3mdamas I had just made an upgrade to VirtualBox so I actually wanted the plugin to update Guest Additions on boot. But I guess if the issue pops up again and there is no other workaround, I might just have to do that. Thanks.

**Comment by j3mdamas** [comment] 2019-09-20 18:25
Yeah, it was only a work-around. I still think this needs fixing upstream, with perhaps better handling of errors during the installation of Guest Additions
