### ISSUE TITLE
Version report is not as expected with VirtualBox 5.1

### ISSUE THREAD

**Issue by allanlewis** [dotless-de/vagrant-vbguest#224] opened 2016-07-19 09:22 UTC
With VirtualBox 5.1, the version reported by VBoxService includes some extra information, which `vbguest` isn't expecting. This causes the following warning message:

```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.1.0 r108711
VBoxService inside the vm claims: 5.1.0
Going on, assuming VBoxService is correct...
```

(The message is actually printed twice, which I assume is an unrelated issue.)

**Comment by allanlewis** [comment] 2016-07-19 09:23
I'm using Fedora 23 with `VirtualBox-5.1.5.1.0_108711_fedora22-1` from the Oracle repo, and the latest version of `vbguest`, 0.11.0.

**Comment by apeabody** [comment] 2016-07-19 17:30
Hi @allanlewis, this was resolved in [0.12.0](https://github.com/dotless-de/vagrant-vbguest/blob/v0.12.0/CHANGELOG.md).  `vagrant plugin update` should hopefully do the trick.

**Comment by richard-scott** [comment] 2016-07-22 13:55
I've an odd output:

```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.20
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
```
I've recently upgraded from 5.0.20 to 5.1.x, maybe something went wrong with that?
Oh, and I'm running with vagrant-vbguest-0.12.0 and VirtualBox-5.1.2.

**Comment by apeabody** [comment] 2016-07-22 17:21
Hi @richard-scott, in this case I'm assuming the old kernel modules were still in use so the new ones couldn't be loaded.  Most likely restarting the box to load the new ones with 'vagrant reload' will resolve the issue.

**Comment by hkjorgensen** [comment] 2016-07-22 18:50
I'm also seeing this with v5.1.2 - never had problems before. Running up-to-date OS X

**Comment by apeabody** [comment] 2016-07-22 21:07
Perhaps it has something to do with the new module rebuilding technique in VirtualBox's 5.1.x guest modules?  I did note in the cases where I was able to reproduce the module version difference, the installer suggested a reboot several lines prior.  Perhaps in a future version vbguest can parse for this and trigger a reload.

https://www.virtualbox.org/wiki/Changelog
- Linux installers: no longer rely on DKMS for module rebuilding

**Comment by richard-scott** [comment] 2016-07-23 20:03
I've removed the 5.0.x install rpm via yum, rebooted and yum installed 5.1.2. I did not "upgrade" as normal. The removal of the older RPM removed all 'old' kernel modules etc.
I have rebooted multiple times and I still get the problem.

It is odd, as on starting the VM I get this:

```
[default] GuestAdditions versions on your host (5.1.2) and guest (5.0.20) do not match.
```

and later on I get told this:

```
tdin: is not a tty
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.20
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.20
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.0.20
    default: VirtualBox Version: 5.1
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
```

Something is mixed up somewhere as its getting all confused about version numbers.

**Comment by motou** [comment] 2016-08-04 15:08
same issue here:

```
✗ vagrant vbguest --status
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
[vm] GuestAdditions seems to be installed (5.1.2) correctly, but not running.
```

The virtualBox is installed by Homebrew cask and updated to the newest version.

I've noticed that the vm doesn't reboot from itself durch the vagant up:

```
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Installing Virtualbox Guest Additions 5.1.2 - guest version is 4.3.36
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.2 Guest Additions for Linux...........
VirtualBox Guest Additions installer
Removing installed version 4.3.36 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
vboxadd.sh: Building Guest Additions kernel modules.
vboxadd.sh: You should restart your guest to make sure the new modules are actually used.
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
vagrant_vbguest.machine_loop_guard
```

**Comment by adecarolis** [comment] 2016-08-10 17:31
+1
Running up-to-date OSX

`Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.2.0
VBoxService inside the vm claims: 5.1.2
Going on, assuming VBoxService is correct...
[default] GuestAdditions seems to be installed (5.1.2) correctly, but not running.`

**Comment by uessy-akr** [comment] 2016-11-10 14:57
I got same messages with VirtualBox 5.1.8 and vagrant-vbguest 0.12.0.

```
Installing Virtualbox Guest Additions 5.1.8 - guest version is 5.0.24
```

```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.24
VBoxService inside the vm claims: 5.1.8
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.24
VBoxService inside the vm claims: 5.1.8
Going on, assuming VBoxService is correct...
```

and it disappeared  after I updated vagrant-vbguest to [0.13.0](https://github.com/dotless-de/vagrant-vbguest/blob/v0.13.0/CHANGELOG.md) .

```
$ vagrant plugin update
Updating installed plugins...
Updated 'vagrant-vbguest' to version '0.13.0'!
```

on `vagrant up` : 

```
==> default: Machine booted and ready!
[default] GuestAdditions 5.1.8 running --- OK.
==> default: Checking for guest additions in VM...
```

```
$ vagrant vbguest --status
[default] GuestAdditions 5.1.8 running --- OK.
```

Is this resolved in [0.13.0](https://github.com/dotless-de/vagrant-vbguest/blob/v0.13.0/CHANGELOG.md) ?

**Comment by mjosef89** [comment] 2016-11-17 12:39
Unfortunately, not.

Host: Windows 7
Guest: Ubuntu 14.04

Vagrant: 1.8.7
vagrant-vbguest: 0.13.0
VirtualBox: 5.1.8

Result on every vagrant up:

```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.8
Going on, assuming VBoxService is correct...
[default] GuestAdditions 5.1.8 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.1.8
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.1
```
And 
```
$ vagrant vbguest --status
[default] GuestAdditions 5.1.8 running --- OK.
```

But for whatever reason when I "vagrant up" a VM with 14.04 but different Base-Box everything works fine
during vagrant up:

`[default] GuestAdditions 5.1.8 running --- OK.`

Does someone knows a solution other than "config.vbguest.auto_update = false"?

**Comment by n-rodriguez** [comment] 2017-01-25 17:54
Hi! Got the same here with Archlinux and Virtualbox 5.1.12 :

```
[default] GuestAdditions versions on your host (5.1.12) and guest (4.1.42) do not match.
stdin: is not a tty
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.2.0-4-amd64 is already the newest version.
linux-headers-3.2.0-4-amd64 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Copy iso file /usr/lib/virtualbox/additions/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
stdin: is not a tty
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.1.12 - guest version is 4.1.42
stdin: is not a tty
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.12 Guest Additions for Linux...........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
vboxadd.sh: Building Guest Additions kernel modules.
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.
stdin: is not a tty

Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.1.42
VBoxService inside the vm claims: 5.1.12
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.1.42
VBoxService inside the vm claims: 5.1.12
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.1.42
    default: VirtualBox Version: 5.1
```

**Comment by dzschille** [comment] 2017-04-19 13:31
Same here.

- Vagrant 1.9.3
- VirtualBox 5.1.20 r114628
- vagrant-vbguest (0.13.0)

```

==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.26
VBoxService inside the vm claims: 5.1.20
Going on, assuming VBoxService is correct...
[default] GuestAdditions 5.1.20 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.26
VBoxService inside the vm claims: 5.1.20
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.0.26
    default: VirtualBox Version: 5.1

```
After reinstalling the GuestAdditions everything is fine now:

```
$ vagrant vbguest --do install --force
$ vagrant reload
...
==> default: Machine booted and ready!
[default] GuestAdditions 5.1.20 running --- OK.

```

**Comment by YousefSaber** [comment] 2018-04-16 11:51
@dzschille 

vbguest v0.15.1 

your steps didn't work out for me 

```

$ vagrant vbguest --do install --force
[default] GuestAdditions 5.2.8 running --- OK.
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
linux-headers-3.13.0-142-generic is already the newest version.
The following packages were automatically installed and are no longer required:
  acl at-spi2-core colord dconf-gsettings-backend dconf-service libasound2
  libasound2-data libatk-bridge2.0-0 libatspi2.0-0 libcairo-gobject2
  libcanberra-gtk3-0 libcanberra-gtk3-module libcanberra0 libcolord1
  libcolorhug1 libdconf1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libexif12 libfontenc1 libgd3 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa
  libgphoto2-6 libgphoto2-l10n libgphoto2-port10 libgtk-3-0 libgtk-3-bin
  libgtk-3-common libgudev-1.0-0 libgusb2 libice6 libieee1284-3 liblcms2-2
  libllvm3.4 libltdl7 libnotify-bin libnotify4 libogg0 libpciaccess0 libsane
  libsane-common libsm6 libtdb1 libtxc-dxtn-s2tc0 libv4l-0 libv4lconvert0
  libvorbis0a libvorbisfile3 libvpx1 libwayland-client0 libwayland-cursor0
  libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-sync1 libxfont1 libxkbcommon0 libxkbfile1 libxmu6 libxpm4
  libxshmfence1 libxt6 libxtst6 libxxf86vm1 notification-daemon
  sound-theme-freedesktop x11-common x11-xkb-utils xfonts-base
  xfonts-encodings xfonts-utils xserver-common xserver-xorg-core
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
Forcing installation of Virtualbox Guest Additions 5.2.8 - guest version is 5.2.8
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.8 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 5.2.8 of VirtualBox Guest Additions...
vboxadd-service.sh: Stopping VirtualBox Guest Addition service.
You may need to restart your guest system to finish removing the guest drivers.
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
VirtualBox Guest Additions: Starting.
An error occurred during installation of VirtualBox Guest Additions 5.2.8. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
VirtualBox Guest Additions: Starting.
/etc/init.d/vboxadd: 256: /etc/init.d/vboxadd: cannot create : Directory nonexistent
Unmounting Virtualbox Guest Additions ISO from: /mnt


```

 ```
vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.2.8
Going on, assuming VBoxService is correct...
[default] GuestAdditions 5.2.8 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   4.3.36
VBoxService inside the vm claims: 5.2.8
Going on, assuming VBoxService is correct...
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.2
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/youse/Desktop/Ubuntu 14.04
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

**Closed** 2019-01-18 21:17 UTC
Labels: wontfix
